### ISSUE TITLE
Create build.rs

### ISSUE THREAD

**Issue by dmadisetti** [AnotherGroupChat/maeve#21]
Make a build.rs file to replace build.sh, hook it up to Cargo.toml. Should have same functionality (if not more)

**Comment by andrewzah** [comment]
Would be simple enough: you can add 
```toml
[package]
...
build = "build.rs"
```
in `cargo.toml`, and then it'll be run whenever you do `cargo build`, etc. [Reference](https://doc.rust-lang.org/cargo/reference/build-scripts.html)

However, to get custom name functionality, you'd likely have to pass in a variable. Something like:
```
MAEVE_GAME=game_default cargo build
```

**Comment by dmadisetti** [comment]
Yep, and ideally should build protos and warn if protoc is not available.
