### ISSUE TITLE
Reworking Action proto

### ISSUE THREAD

**Issue by pbateman828** [AnotherGroupChat/maeve#26]
If the parser succeeds in digesting the input, it passes three pieces of information on to the rest of the program:
1. The verb
2. The direct object
3. The indirect object

This issue involves changing the action proto to represent the listed objects

**Comment by dmadisetti** [comment]
Inspired by OG Zork Interpreter.

In particular, see if we want to go down the route of totally representing ZIL (Zork Implementation Language) http://xlisp.org/zil.pdf
