### ISSUE TITLE
Conditionally setting up ncurses

### ISSUE THREAD

**Issue by pbateman828** [AnotherGroupChat/maeve#4]

**Comment by dmadisetti** [comment]
https://github.com/kkawakam/rustyline

**Comment by kevinlmadison** [comment]
ooh I like rustyline, I'm actually working on something in C right now and learned a couple of methods they used to use under the hood for that sort of thing. It's one of those things you take for granted until you try to make your own terminal based programs lol.

**Comment by dmadisetti** [comment]
Closed with merge
