### ISSUE TITLE
Changing the game state

### ISSUE THREAD

**Issue by pbateman828** [AnotherGroupChat/maeve#9]

**Comment by kevinlmadison** [comment]
What is meant by this issue? @dmadisetti @pbateman828

**Comment by pbateman828** [comment]
The game state is loaded when the player provides the pb binary, so changes to the game state are saved in the player provided save file. Just making sure the changes are saved in the player provided pb file

**Comment by kevinlmadison** [comment]
Should this fall under the same game issue then maybe?

**Comment by pbateman828** [comment]
same game?

**Comment by kevinlmadison** [comment]
Save game, sorry

**Comment by pbateman828** [comment]
It involves the save game issue yes but this is more of in the scope of knowing what the player does such as traversing from level 1 to 2, performing an action or using an item. If there is only one set of matches within the entire game and the player uses the matches then unless the player starts a new game, the player shouldn't be able to use the matches again.

**Comment by pbateman828** [comment]
The save game issue is more of just writing the game state to the provided save file.
